# Generated by Django 4.0.3 on 2022-04-02 23:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jotter',
            fields=[
                ('title', models.CharField(default='JotIT', max_length=200)),
                ('snippet', models.CharField(default='JotIT', max_length=200)),
                ('detail', models.TextField(default='JotIT')),
                ('important', models.BooleanField(default=False)),
                ('stamp', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
